#!/bin/sh
export WEKA_DIR=$HOME/weka-3-4
export CLUS_DIR=$HOME/Clus
export HMC_AVG_SINGLE_DIR=$CLUS_DIR/addon/hmc/HMCAverageSingleClass
echo $HMC_AVG_SINGLE_DIR
java -cp "$HMC_AVG_SINGLE_DIR/bin:$CLUS_DIR/bin:$WEKA_DIR/weka.jar:$CLUS_DIR/commons-math-1.0.jar" HMCAverageSingleClass $*
