#!/bin/sh
export WEKA_DIR=$HOME/NoCsBack/weka-3-4
export CLUS_DIR=$HOME/Clus
export HMC_AVG_SINGLE_DIR=$HOME/files/eclipse/clusaddon/HMCConvertDAGData
echo $HMC_AVG_SINGLE_DIR
java -Xmx500000000 -cp "$HMC_AVG_SINGLE_DIR/bin:$CLUS_DIR/bin:$WEKA_DIR/weka.jar:$CLUS_DIR/commons-math-1.0.jar" HMCConvertDAGData $*
