#!/bin/sh
VERS="2.5"
rm -rf release
mkdir -p release
mkdir -p release/Clus
cp addon/script/compile.sh release/Clus/
cp addon/script/clus.sh release/Clus/
cp -r clus addon data docs jars jeans sit LICENSE.txt README.txt release/Clus/
rm -rf release/Clus/jeans/graph/trayicon
rm -rf release/Clus/data/test_m5_prune
cd release/Clus/data
perl cleanall
cd ../../../
find release/Clus/ -name "CVS" -exec rm -rf {} \;
find release/Clus/ -name ".svn" -exec rm -rf {} \;
find release/Clus/ -name ".cvsignore" -exec rm -f {} \;
find release/Clus/data -name "debug.txt" -exec rm -f {} \;
find release/Clus/data -name "*.model" -exec rm -f {} \;
find release/Clus/data -name "*.xval" -exec rm -f {} \;
find release/Clus/data -name ".gle" -exec rm -rf {} \;
cd release/Clus/
. compile.sh
cd bin
jar xvf ../jars/commons-math-1.0.jar
jar xvf ../jars/jgap.jar
jar cvfm ../Clus.jar ../../../addon/script/manifest *
cd ../../
rm -rf Clus/bin
mkdir -p Clus/bin
echo $VERS > Clus/VERSION.txt
zip -r Clus-$VERS.zip Clus
cd ..
ls -al release
