#!/usr/local/gnu/bin/perl
open(FILE,".cvsignore") || die "Can't open ignore file";
while ($line = <FILE>) {
	chop($line);
	if (!($line =~ /^\s*$/)) {
		$find = "find . -name \"$line\" -exec rm {} \\;";
		print "$find\n";
		system($find);
	}
}
close(FILE);
system("rm -rf church_FUN/AUC_average");
